version: '3'

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'strapi_php:7.1.x-webserver'
    restart: 'always'
    ports:
      - "8006:80"
      - "4439:443"
    links: 
      - postgres
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2

  strapi:
    image: strapi/strapi
    container_name: 'strapi_webserver'
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: strapi
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./www/backend-landing-api:/srv/app
    ports:
      - '1338:1337'
    depends_on:
      - postgres

  postgres:
    # image: postgres:12.3-alpine
    build: 
      context: ./bin/postgres/12/alpine
    container_name: 'strapi_postgres'
    # privileged: true
    restart: always
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    ports:
      - '5433:5432'
    volumes: 
      - ${POSTGRES_SQL_DATA_DIR-./data/postgres}:/var/lib/postgresql/data
      - pgdata:/var/lib/postgresql/data
      - ${POSTGRES_SQL_LOG_DIR-./logs/postgres}:/var/log/postgresql

  mongo:
    image: mongo
    container_name: 'strapi-mongo'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: strapi
    volumes:
      - mongodata:/data/db
    ports:
      - '27018:27017'

  mysql:
    build: ./bin/mysql
    container_name: strapi_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: strapi
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    ports:
      - '3340:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'strapi-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8090:80'
    volumes: 
      - /sessions

  pgadmin4:
    image: "dpage/pgadmin4"
    # build: 
    #   context: ./bin/pgadmin4
    container_name: 'strapi_pgadmin4'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "15434:80"
    volumes:
      # - ./data/pgadmin4:/var/lib/pgadmin
      - pgadmindata:/var/lib/pgadmin
    depends_on:
      - postgres

  redis:
    image: redis:latest
    container_name: 'strapi-redis'
    restart: always
    ports:
      - "63781:6379"
    volumes:
      - ./storage/redis/data:/data
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  pgdata:
  pgadmindata:
  mongodata:
  mysqldata:
